version: '3'
services:
  nginx:
    image: nginx:1.15
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    depends_on:
      - web
    networks:
      - internet
      - intranet
  web:
    build: .
    depends_on:
      - mysql
      - redis
    volumes:
      - ./flag:/tmp/flag:ro
      - ./dreamer-cms:/dreamer-cms:rw
    restart: always
    networks:
      - intranet
  mysql:
    image: mysql:5.7
    volumes:
      - ./dreamer-cms.sql:/docker-entrypoint-initdb.d/dreamer-cms.sql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dreamer-cms
    restart: always
    networks:
      - intranet
  redis:
    image: redis:latest
    restart: always
    environment:
      - REDIS_ARGS="--requirepass 123456"
    networks:
      - intranet
networks:
  intranet:
        internal: true
        ipam:
            driver: default
  internet:
        ipam:
            driver: default
